### ISSUE TITLE
Unserializable field should not throw error

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#45]
when a field is not serializable, it should not throw an error but rather show an empty object or `[unserializable object]` in the data.

eg:

```
 "exception"  : {
     "$type"  :  "TypeError" ,
     "name"  :  "TypeError" ,
     "message"  :  "Cannot convert object to primitive value" ,
     "stack"  :  "TypeError: Cannot convert object to primitive value
    at Trait.invoke (/nodejsAction/XXJKBPJP/main.js:11351:71)
    at jsonifyForLog (/nodejsAction/XXJKBPJP/main.js:3199:47)
    at map (/nodejsAction/XXJKBPJP/main.js:9323:11)
    at map.next (<anonymous>)
    at each (/nodejsAction/XXJKBPJP/main.js:9151:26)
    at ./node_modules/ferrum/src/sequence.js.curry (/nodejsAction/XXJKBPJP/main.js:8911:5)
    at each [CURRY] (/nodejsAction/XXJKBPJP/main.js:7973:12)
    at obj (/nodejsAction/XXJKBPJP/main.js:9150:3)
    at ./node_modules/@adobe/openwhisk-action-utils/node_modules/@adobe/helix-log/src/serialize-json.js.JsonifyForLog.impl (/nodejsAction/XXJKBPJP/main.js:3209:38)
    at Trait.invoke (/nodejsAction/XXJKBPJP/main.js:11356:12)"
```

**Comment by koraa** [comment]
Could you please provide an example for this and some example code that can be used to reproduce this?

**Comment by tripodsan** [comment]
hmm...I can't reproduce it anymore ATM...

**Comment by koraa** [comment]
Would you like to close this issue or keep it open as a remindert to try and reproduce this?

**Comment by tripodsan** [comment]
close it for now.

**Comment by tripodsan** [comment]
I found a way to reproduce this:

**Comment by koraa** [comment]
So no exception thrown?

This is the expected behavior of the heuristic…it serializes to json unless the data can not be serialized.
We might consider a different heuristic, but I don't think it would be a good idea to just turn anything into json because it would drastically increase the space of false positives…

**Comment by tripodsan** [comment]
using data-logging, we want explicitly use that data for logging. if a field happens to be not serializable, it should just be ignored.
