### ISSUE TITLE
json log formatter fails (silently) when a data field is undefined

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-log#46]
if trying to log json data with an undefined property, the json formatter ignores the data, due to a cought serialization error and just uses the normal serialize mesage. this is very hard to debug :-)

eg:

```
{ Error: No implementation of trait JsonifyForLog for undefined of type undefined.
    at Trait.invoke (/nodejsAction/XXOeiOAf/main.js:9952:17)
    at jsonifyForLog (/nodejsAction/XXOeiOAf/main.js:1532:47)
    at map (/nodejsAction/XXOeiOAf/main.js:7923:11)
    at map.next (<anonymous>)
    at each (/nodejsAction/XXOeiOAf/main.js:7751:26)
    at ./node_modules/ferrum/src/sequence.js.curry (/nodejsAction/XXOeiOAf/main.js:7511:5)
    at each [CURRY] (/nodejsAction/XXOeiOAf/main.js:6573:12)
    at obj (/nodejsAction/XXOeiOAf/main.js:7750:3)
    at ./node_modules/@adobe/helix-log/src/serialize-json.js.JsonifyForLog.impl (/nodejsAction/XXOeiOAf/main.js:1542:38)
    at Trait.invoke (/nodejsAction/XXOeiOAf/main.js:9956:12)
```

suggest to just ignore undefined fields.

ps: Having a distinct separation from data and message would really be good.

**Comment by koraa** [comment]
It does log an error message though, doesn't it?

**Comment by tripodsan** [comment]
> It does log an error message though, doesn't it?

yes. but it doesn't tell you which field is undefined.

**Comment by koraa** [comment]
Uh mentioning the field would be a bit tough to implement; we would have to kind of provide a JSON stack trace (after all the field could be in an array; in a nested-nested-nested-nested object or the root object itself…)

I see the appeal, but I would wait with such a feature until this really bothers us…

**Comment by koraa** [comment]
I suggest you close this or add a maybelater tag at your discretion…
